#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Make data directory if it doesn't exist already
mkdir -p "$DIR/.data"

# shellcheck source=scripts/create_env.bash
. "$DIR/scripts/create_env.bash"

# try to detect and warn user of duplicate variables
. "$DIR/scripts/detect_duplicate_vars.bash"

# try to detect and warn user of old volume mounts
. "$DIR/scripts/detect_old_data.bash"

# Get list of overrides
OVERRIDE_OPTIONS=()
shopt -s nullglob
for f in "$DIR/overrides"/*.yml
do
    OVERRIDE_OPTIONS+=(-f)
    OVERRIDE_OPTIONS+=("$f")
done

# Setup Docker Compose command
# Pass in sudo command if required
set_compose_command() {
    __SUDO=$1
    if $__SUDO docker compose &>/dev/null; then
        DOCKER_COMPOSE_CMD=("$__SUDO" docker compose)
    elif $__SUDO docker-compose &>/dev/null; then
        DOCKER_COMPOSE_CMD=("$__SUDO" docker-compose)
    else
        echo "Please make sure Docker Compose is installed"
    fi
}

if docker info &>/dev/null; then
    set_compose_command ""
else
    set_compose_command "sudo"
fi

exec "${DOCKER_COMPOSE_CMD[@]}" -f docker-compose.yml "${OVERRIDE_OPTIONS[@]}" build \
     --build-arg LOCAL_USER_ID="$(id -u "${USER:?}")" \
     --build-arg LOCAL_GROUP_ID="$(id -g "${USER:?}")" "$@"
