version: '3'
services:
  tor:
    build:
      context: docker/tor
    volumes:
      - ./tor_data:/var/lib/tor
      - ./tor_config:/etc/tor
#      - ./bitcoin_data:/home/alice/.bitcoin
#      - ./logfiles:/root/logfiles
#      - ./lnd_data:/home/alice/.lnd
#      - ./node_data:/home/alice/.node
#    environment:
#      LOCAL_USER_ID: ${LOCAL_USER_ID:-9001}
    ports:
      - "10009:10009"
      - "8080:8080"
  bitcoin:
    image: alpine
    network_mode: service:tor
    command: sh -c "while true; do date; sleep 5; done"
    volumes:
      - ./tor_data:/var/lib/tor
      - ./tor_config:/etc/tor

  #bitcoin:
  #  hostname: bitcoin
  #  image: ruimarinho/bitcoin-core
  #  volumes:
  #    - ./tor_data:/var/lib/tor
