version: '3.7'

# Only Tor and Bitcoin are considered core services.
# Even these services can be changed by adding an override in the 'override' directory.
services:
  tor:
    build:
      context: docker/tor
    restart: always
    volumes:
      - ${_SRC_TOR_DATA:?}:${_DST_TOR_DATA:?}
      - ${_SRC_TOR_CONFIG:?}:${_DST_TOR_CONFIG:?}
    env_file:
      - .env

  bitcoin:
    build:
      context: docker/bitcoin
    restart: always
    network_mode: service:tor
    depends_on:
      - tor
    volumes:
      - ${_SRC_TOR_DATA:?}:${_DST_TOR_DATA:?}:ro
      - ${_SRC_TOR_CONFIG:?}:${_DST_TOR_CONFIG:?}:ro
      - ${_SRC_BITCOIN:?}:${_DST_BITCOIN:?}
    env_file:
      - .env
      - env/bitcoin.env
