version: '3.7'

x-tor-data-ro: &tor-data-ro "./tor_data:/var/lib/tor:ro"
x-tor-config-ro: &tor-config-ro "./tor_config:/etc/tor:ro"
x-rpc-settings: &rpc-settings
  RPCPASSWORD:
  RPCUSER:
x-network-settings: &network-settings
  TESTNET_NUM:
  ELECTRS_NETWORK:

services:
  tor:
    build:
      context: docker/tor
    restart: always
    volumes:
      - ./tor_data:/var/lib/tor
      - ./tor_config:/etc/tor

  bitcoin:
    build:
      context: docker/bitcoin
    restart: always
    network_mode: service:tor
    depends_on:
      - tor
    volumes:
      - *tor-data-ro
      - *tor-config-ro
      - ./bitcoin_data:/home/bitcoin/.bitcoin
    environment:
      <<: *rpc-settings
      <<: *network-settings
