version: '3.7'

x-tor-data-ro: &tor-data-ro "./tor_data:/var/lib/tor:ro"
x-tor-config-ro: &tor-config-ro "./tor_config:/etc/tor:ro"
x-rpc-settings: &rpc-settings
  RPCPASSWORD:
  RPCUSER:
x-lnd-settings: &lnd-settings
  LND_ALIAS:
  LND_COLOR:

services:
  tor:
    build:
      context: docker/tor
    restart: always
    volumes:
      - ./tor_data:/var/lib/tor
      - ./tor_config:/etc/tor
    ports:
      - "10009:10009"
      - "8080:8080"

  bitcoin:
    build:
      context: docker/bitcoin
    restart: always
    network_mode: service:tor
    volumes:
      - *tor-data-ro
      - *tor-config-ro
      - ./bitcoin_data:/home/bitcoin/.bitcoin
    environment:
      <<: *rpc-settings

  lnd:
    build:
      context: docker/lnd
    restart: always
    network_mode: service:tor
    volumes:
      - *tor-data-ro
      - *tor-config-ro
      - ./lnd_data:/home/lnd/.lnd
    command: lnd
    environment:
      <<: *rpc-settings
      <<: *lnd-settings
